apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-pulse-tracker
  labels:
    app: market-pulse-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: market-pulse-tracker
  template:
    metadata:
      labels:
        app: market-pulse-tracker
    spec:
      containers:
        - name: market-pulse-tracker
          image: your-dockerhub-username/market-pulse-tracker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 5 