apiVersion: v1
kind: Service
metadata:
  name: market-pulse-service
  labels:
    app: market-pulse-tracker
spec:
  type: ClusterIP
  selector:
    app: market-pulse-tracker
  ports:
    - name: http
      port: 80
      targetPort: 5000 